http:
    port: 8080
database:
    driver: postgres
    user: postgres
    password: postgres
    dbname: market
    host: localhost
    port: 5432
    sslmode: disable
logs:
    folder: logs/
    name: logs.txt
files:
    folder: pictures/
post:
    server: smtp.yandex.ru:465
    user: user@yandex.ru
    password: password